name: Python tests

on: push

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check PEP8 compliance
        run: |
          black --check --verbose ./ # src service
        continue-on-error: true
      - name: Lint with mypy
        run: |
          mypy src
        continue-on-error: true
      - name: Unit tests with pytest
        run: |
          pytest --cov=src tests
        continue-on-error: true
      - name: Integration tests with pytest
        run: |
          pytest ./ # --cov=service service
        continue-on-error: true 
        
# TODO: delete continue-on-error
